### ISSUE TITLE
Revisión script para la nueva version ogame v6/ Revision script for the new version v6 ogame

### ISSUE THREAD

**Issue by Extreme10** [EliasGrande/OGameTradeCalculator#1]
Buenas!!!!

Para poder seguir usando este scripts, tiene que ser revisado y actualizado hasta la fecha para la nueva version v6 de ogame que salió posterior a la fecha de emisión.
Si es revisado y actualizado, se podria seguir usando.

Un saludo y gracias.

Good !!!!

To continue using the scripts , it must be reviewed and updated to date for the new version v6 ogame that came after the date of issue.
If revised and updated , it could still be used .

Greetings and thank you.

**Comment by EliasGrande** [comment]
Estoy bastante liado últimamente, si tengo tiempo lo miro, pero no prometo nada.

El código sin comprimir ya está parcheado para los nuevos dominios de gameforge, pero la release compriida aún no. Pruébalo si puedes y me dices si funciona correctamente:

https://raw.githubusercontent.com/EliasGrande/OGameTradeCalculator/master/src/ogame-trade-calculator.user.js

**Comment by Extreme10** [comment]
Si, funciona a la perfección en chrome.... Lo puedo exponer en el foro ogame español para que lo legalicen como scripts????

Aunque no se si deberías ser tu el que lo exponga. Este es el hilo en el que exponen los scripts a legalizar:

http://board.es.ogame.gameforge.com/board859-ogamelacomunidad/board860-comunidad/board422-utilidadesyskinsparaogame/1312581-nuevaconsultor%C3%ADadescriptscomplementosyutilidadesparaogamebydanimanza/?s=cd12492901941a7e5ff5dd2afe209d54fc93308d

Y esta en la que ya están los legalizados:

http://board.es.ogame.gameforge.com/board859-ogamelacomunidad/board860-comunidad/board422-utilidadesyskinsparaogame/1312632-nuevalistadescriptscomplementospermitidosenogamev6xx/

De momento lo dejo desinstalado hasta que no lo legalicen.

Cuando puedas hacer la release comprimida avisa.

Un saludo y muchas gracias ;)

**Comment by EliasGrande** [comment]
Cuando tenga un rato saco la release y aviso en los hilos originales de mis scipts en Ogame Origin, que desde ahí ya lo legalizan para todos los países. Gracias por avisar.

**Comment by EliasGrande** [comment]
Ya están las releases comprimidas disponibles, pero no tengo tiempo en estos momentos para probarlas en profundidad, si puedes prueba mis scripts y por la tarde pido su re-legalización.

Scripts y su foro de legalización:
- OGameTradeCalculator: [GitHub (instalar)](https://github.com/EliasGrande/OGameTradeCalculator) / [Ogame Origin (legalizar)] (http://board.origin.ogame.gameforge.com/board7-archives/board115-archive-user-project-s/4367-ogame-trade-calculator/)
- CerealOgameStats: [GitHub (instalar)](https://github.com/EliasGrande/CerealOgameStats) / [Ogame Origin (legalizar)] (http://board.origin.ogame.gameforge.com/board7-archives/board115-archive-user-project-s/4107-cerealogamestats/)
- OGameHiddenColony: [GitHub (instalar)](https://github.com/EliasGrande/OGameHiddenColony) / [Ogame Origin (legalizar)] (http://board.origin.ogame.gameforge.com/board7-archives/board115-archive-user-project-s/4805-ogame-hidden-colony/)

**Comment by Extreme10** [comment]
- Ogamecalculator funcionamiento perfecto en chrome y firefox.
- OgameHiddenColony va perfecto en firefox, pero en chrome delante de las fechas aparece un cuadradito blanco. Si puedes repararlo de lujo. Por lo demás el funcionamiento perfecto.
- CerealOgameStats funciona el formato de texto para exportar al foro, pero los otros de datos que dan opción para copiar texto no se bien para que son, porque ese formato no lo detecta ni para mensajes circulares( no se bien para que son, asi que no se si es que son erroneos o son así). Su funcionamiento es perfecto en chrome y firefox.

Pegale el ultimo retoque y ya estaría listo para su legalización :) Vuelvo a quitarlos.
Lo dicho, los vuelvo a desinstalar a la espera del ultimo retoque y posterior legalización. Gracias ;)

**Comment by EliasGrande** [comment]
Scripts legalized on Janyary 2016, closing issue.
