### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by comfreak89** [EliasGrande/OGameTradeCalculator#2]
{
	// Number separators
	THO_SEP : ".",
	DEC_SEP : ",",
	// Menu button
	MENU    : "Handel",
	// Window title
	TITLE   : "Handelsrechner",
	CONFIG  : "Einstellungen",
	// Actions
	ACTION  : "Aktion",
	BUY     : "Ich kaufe",
	SELL    : "Ich verkaufe",
	// Ratio
	RATIO   : "Kurs",
	ILLEGAL : "illegal",
	MAX     : "Maximum",
	REG     : "Regulär",
	MIN     : "Minimum",
	// Output
	IN_EXCH : "Im Austausch für",
	RESULT  : "Ergebnis",
	SEND    : "Ich sende",
	RECEIVE : "Ich erhalte",
	RES     : "Ressourcen",
	// Ships
	LC_SHIP : "GT", // Abb. of "Large Cargo Ship"
	SC_SHIP : "KT", // Abb. of "Small Cargo Ship"
	OR      : "oder", // e.g. 100 (LC) or 500 (SC)
	// Message
	MESSAGE : "Nachricht",
	// Place of delivery
	WHERE   : "Lieferadresse",
	PLANET  : "Planet",
	MOON    : "Mond",
	CUR_PLA : "Aktueller Planet",
	SEL_CUR : "Wähle den aktuellen Planeten oder Mond",
	// Config » Ratio list
	RAT_LST : "Kursliste",
	NAME    : "Name",
	LEGAL   : "Legal",
	YES     : "Ja",
	NO      : "Nein",
	DEFAULT : "Standard",
	NEW     : "Neu",
	// Config » Default values
	DEF_VAL : "Standardwerte",
	// Config » Abbs & keys
	ABB_KEY : "Abkürzungen und Tasten für Autovervollständigung",
	USE_ABB : "Benutze Abkürzungen wenn möglich",
	UNABB   : "Felder nicht abkürzen, wenn die Maus über ihnen ist",
	ABB_MIL : "Abkürzung für Millionen",
	ABB_THO : "Abkürzung für Tausend",
	KEY_MIL : "Taste für Millionen (6 Nullen)",
	KEY_THO : "Taste für Tausend (3 Nullen)",
	// Config » Message tpl
	MES_TPL : "Nachrichtenvorlage",
	RES_DTP : "Standardvorlage wiederherstellen",
	// Config » Import / Export
	IE_CONF : "Import / Export Konfiguration",
	IMPORT  : "Import",
	EXPORT  : "Export",
	// Config » Buttons
	ACCEPT  : "Akzeptieren",
	CANCEL  : "Abbrechen",
	RES_DEF : "Standardeinstellungen wiederherstellen",
	// Config » Contact
	CONTACT : "Kontaktinformation"
}

**Comment by EliasGrande** [comment]
Hi, sorry for not answering before, I was on vacations, this afternoon/night I'll add your contribution, thanks. Is good to see that the script is still being used after all this time, any issues with new versions of OGame or still works fine?

**Comment by comfreak89** [comment]
Hi, no problem. Jeah, I found 1 issue: If you are in some menus and open Trade C. and type a number in action with a shortcut, it will not autocomplete.

Example:

- open supply
- open Trade C.
- type into metal 1 and m (auto complete for million)
- nothing happens

I have the same behavior in facilities, research, shipyard and defence. So in short: everywhere you can build something.

Otherwise: thank you for the great script! :+1:

**Comment by EliasGrande** [comment]
Translation added, update the script and tell me if it works fine on german servers.

**Comment by EliasGrande** [comment]
Just uploaded another version (3.0.3) fixing the AntGame issue with the shortcut keys.

**Comment by comfreak89** [comment]
Translation and fix works perfectly, Thanks! 👍
